baseURL: "https://andreashih.github.io"
languageCode: "en-us"
title: "Andrea Shih"
theme: hugo-profile

Paginate: 3
disqusShortname: theandreajournal
googleAnalytics: G-21NGD0NV8X

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      #title: Blog posts
      url: /blog
      weight: 1
    
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Andrea Shih"
  description: #Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  #color preference
  color:
    textColor:
    secondaryTextColor:
    backgroundColor:
    secondaryBackgroundColor:
    primaryColor: "#D198C5FF"
    secondaryColor:

    darkmode:
      textColor:
      secondaryTextColor:
      backgroundColor:
      secondaryBackgroundColor:
      primaryColor: "#D198C5FF"
      secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Andrea Shih."
    subtitle: "I develop LLM applications."
    content: 
    image: /images/bio-photo.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1Rc9YPEi__PuUVvseOdJyLTr_O25FoFrFfn_OiC7Xcig/edit?usp=sharing"
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/andreashih
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/andreashih/
        - icon: fa fa-envelope
          url: mailto:cfshih97@gmail.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    #image: "/images/me.png"
    content: |-
           I'm a **Software Engineer** specializing in **Large Language Models (LLMs)** and **Generative AI** with a background in **Computational Linguistics**. I build user-centric AI solutions that enhance information retrieval and knowledge management.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"

  # Experience
  experience:
    enable: True
    # title: "Custom Name"
    items:
      - job: "Senior Software Engineer"
        company: "Delta Electronics"
        companyUrl: "https://deltaww.com/"
        date: "Nov 2023 - present"
        info:
          enable: true
          content: "Last updated: Feb 2025"
        content: |
          - Designed and deployed **5+ domain-specific chatbots**, optimizing knowledge accessibility and streamlining business workflows through user-centric AI solutions.
          - Built RAG chatbots with content summarization, inline references, streaming responses, and multi-turn interactions, improving **information retrieval** and **user engagement**.
          - Developed APIs in Python & FastAPI, transforming PDF, PPTX, and MP4 files into **searchable vector database entries**, boosting knowledge discovery.
          - Engineered a **RAGAS evaluation** API, automating LLM performance assessment and **improving summary accuracy**.
          - Designed intuitive **front-end demo webpages**, increasing client engagement and product accessibility.
          - Mentored an intern in **GraphRAG chatbot development**, fostering expertise in **project management**.
      - job: "Data Scientist"
        company: "Wistron"
        companyUrl: "https://www.wistron.com/"
        date: "Sep 2022 - Oct 2023"
        info:
          enable: true
          content: "Last updated: Feb 2025"
        content: |
          - Developed a machine learning model that achieved **90%+ accuracy** and **cut task completion time by 50%**, optimizing supply chain efficiency.
          - Built an **end-to-end data solution** with Docker containerization and PostgreSQL database management, enabling scalable and efficient workflows.
          - Delivered strategic business insights through **demand forecasting**, **data analytics**, and **visualization** using Python and R, driving data-informed decisions.
          - Optimized automated PCB placement performance with **genetic algorithms**, improving manufacturing precision and efficiency.

        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Master of Linguistics"
        school:
          name: "National Taiwan University"
          url: "https://www.ntu.edu.tw/"
        date: "2019 - 2022"
        GPA: "4.16 out of 4.3"
        content: |-
          Concentrations: 
            - computational linguistics
            - corpus linguistics

          Master's thesis:
            - Semantic Classification of Mandarin Chinese Constructions [[LINK]](https://www.airitilibrary.com/Publication/alDetailedMesh1?DocID=U0001-2208202200052700&PublishTypeID=P003)
          
          My publications can be found in [Google Scholar](https://scholar.google.fr/citations?user=7Q3wOsYAAAAJ).

      - title: "Bachelor of Foreign Languages and Literature"
        school:
          name: "National Sun Yat-sen University"
          url: "https://www.nsysu.edu.tw/"
        date: "2015 - 2019"
        GPA: "4.1 out of 4.3"
        content: |-
          Graduated with distinguished undergraduate award.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Interactive Co-varying Collexeme Analysis (python version)
        content: An app that demonstrates the relations between word pairs and constructions. Written with python.
        image: /images/projects/mountains4.jpg
        featured:
          name: Demo
          link: https://andreashih.shinyapps.io/cca-python1/
        badges:
          - "python"
        links:
          - icon: fab fa-github
            url: https://github.com/andreashih/shinyapp-python

      - title: Interactive Co-varying Collexeme Analysis (R version)
        content: An app that demonstrates the relations between word pairs and constructions. Written with R.
        image: /images/projects/mountains3.jpg
        featured:
          name: Demo
          link: https://andreashih.shinyapps.io/covarying_collexeme_analysis/
        badges:
          - "R"
        links:
          - icon: fab fa-github
            url: https://github.com/andreashih/covarying-collexeme-analysis

      - title: DOCX Search and Manipulation
        content: A tool to search and manipulate .DOCX files with python.
        image: /images/projects/mountains2.jpg
        # featured:
        #   name: Demo
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "python"
        links:
          - icon: fab fa-github
            url: https://github.com/andreashih/docx-search-manipulation

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: College Student Research Creativity Award
        content: Ministry of Science and Technology (2019)
        #url: https://example.com
      - title: Distinguished Undergraduate Award
        content: Department of Foreign Languages and Literature (2019)

  # Contact
  contact:
    enable: false
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: cfshih97@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      #github: https://github.com/andreashih
      #linkedin: https://www.linkedin.com/in/andreashih/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
